# Generated by Django 4.0.1 on 2022-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_note_color_alter_note_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
